//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeInWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressInformation
    {
        public int id { get; set; }
        public Nullable<int> person_id { get; set; }
        public Nullable<double> LivingRooms { get; set; }
        public Nullable<double> BedRooms { get; set; }
        public Nullable<double> Kitchen { get; set; }
        public Nullable<double> SquareFootSize { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
