//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeInWebAPI.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeInEntities : DbContext
    {
        public HomeInEntities()
            : base("name=HomeInEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressInformation> AddressInformations { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<LastHiredBy> LastHiredBies { get; set; }
        public virtual DbSet<PaymentProfile> PaymentProfiles { get; set; }
        public virtual DbSet<PersonRole> PersonRoles { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<WorkerAvailability> WorkerAvailabilities { get; set; }
        public virtual DbSet<WorkerExperience> WorkerExperiences { get; set; }
        public virtual DbSet<WorkerSchedule> WorkerSchedules { get; set; }
        public virtual DbSet<WorkerSkill> WorkerSkills { get; set; }
        public virtual DbSet<Person> Person { get; set; }
    }
}
