//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeInWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentProfile
    {
        public int id { get; set; }
        public string type { get; set; }
        public int person_id { get; set; }
        public string billing_address { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
