//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeInWebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerAvailability
    {
        public int id { get; set; }
        public int worker_Id { get; set; }
        public Nullable<int> MilesWantToDrive { get; set; }
        public string DaysAvailable { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
